### ISSUE TITLE
Setup dependencies error

### ISSUE THREAD

**Issue by peersky** [bugout-dev/moonworm#18]
running 
` python3 -m setup.py install`

Is causing following error: 
```
Processing dependencies for moonworm==0.0.4
error: typing-extensions 4.0.0 is installed but typing-extensions<4,>=3.7.4 is required by {'trie'}
```

**Comment by Yhtiyar** [comment]
Fixed on: [commit](https://github.com/bugout-dev/moonworm/commit/8f3e94967abb05506b6e901c0ee335135e93a75c)
