### ISSUE TITLE
Make `-v` `--version` argument

### ISSUE THREAD

**Issue by Yhtiyar** [bugout-dev/moonworm#37]
Need  to provide ability to get version of `moonworm` from cli

**Comment by twelsh37** [comment]
Id like to take a stab at this. I'm guessing it shouldgo in cli.py

**Comment by Yhtiyar** [comment]
@twelsh37, cool. 
Yes, it will go to `cli.py`
Basically `moonworm -v` should print current version from `version.py`

**Comment by zomglings** [comment]
@twelsh37 , @Yhtiyar : It might be easier to add a subcommand called `moonworm version`. Getting the right behaviour for `moonworm -v` requires messing with `arparse` actions, which can be kind of a pain.

**Comment by Yhtiyar** [comment]
resolved in #68
